name: Elixir Test CI

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Linux OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '24.0'
            elixir-version: '1.13'
          - otp-version: '25.0'
            elixir-version: '1.14'

    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{matrix.pair.otp-version}}
        elixir-version: ${{matrix.pair.elixir-version}}
    - name: Install Dependencies
      run: mix deps.get
    - name: compile
      run: mix compile --warnings-as-errors
    - name: Check formatting
      run: mix format --check-formatting
    - name: Run linting
      run: mix credo --strict
    - name: Run Tests
      run: mix test